-- Barca Family: run in a dedicated Supabase project, SQL Editor, as postgres.
-- Repeatable; existing votes and content are preserved.
BEGIN;
SET LOCAL search_path = public;

CREATE TABLE IF NOT EXISTS players (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL, number INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS player_profiles (player_id TEXT PRIMARY KEY REFERENCES players(id), photo_path TEXT, photo_source TEXT, checked_on TEXT, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS bot_content (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_by TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS matches (id TEXT PRIMARY KEY, opponent TEXT NOT NULL, score TEXT NOT NULL, played_on TEXT NOT NULL, season TEXT NOT NULL, competition TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('draft','open','closed')), closes_at TEXT, demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS match_players (match_id TEXT NOT NULL REFERENCES matches(id), player_id TEXT NOT NULL REFERENCES players(id), position INTEGER NOT NULL, PRIMARY KEY(match_id,player_id));
CREATE TABLE IF NOT EXISTS ballots (match_id TEXT NOT NULL REFERENCES matches(id), user_id TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, submitted INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, PRIMARY KEY(match_id,user_id));
CREATE TABLE IF NOT EXISTS votes (match_id TEXT NOT NULL, user_id TEXT NOT NULL, player_id TEXT NOT NULL, score INTEGER NOT NULL CHECK(score BETWEEN 1 AND 5), PRIMARY KEY(match_id,user_id,player_id), FOREIGN KEY(match_id,user_id) REFERENCES ballots(match_id,user_id), FOREIGN KEY(match_id,player_id) REFERENCES match_players(match_id,player_id));
CREATE INDEX IF NOT EXISTS votes_aggregate ON votes(match_id,player_id);
CREATE INDEX IF NOT EXISTS matches_season ON matches(season,state);
CREATE TABLE IF NOT EXISTS admins (user_id TEXT PRIMARY KEY, role TEXT NOT NULL CHECK(role IN ('owner','admin')));
CREATE TABLE IF NOT EXISTS audit (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, action TEXT NOT NULL, match_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bot_state (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bot_jobs (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, payload TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS bot_jobs_pending ON bot_jobs(state,created_at);
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.players FROM anon, authenticated;
ALTER TABLE public.player_profiles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.player_profiles FROM anon, authenticated;
ALTER TABLE public.bot_content ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.bot_content FROM anon, authenticated;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.matches FROM anon, authenticated;
ALTER TABLE public.match_players ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.match_players FROM anon, authenticated;
ALTER TABLE public.ballots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ballots FROM anon, authenticated;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.votes FROM anon, authenticated;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.admins FROM anon, authenticated;
ALTER TABLE public.audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.audit FROM anon, authenticated;
ALTER TABLE public.bot_state ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.bot_state FROM anon, authenticated;
ALTER TABLE public.bot_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.bot_jobs FROM anon, authenticated;
INSERT INTO players(id,name,role,number) VALUES('garcia','Жоан Гарсия','Вратарь',1) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('garcia','/portraits/garcia.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/76e07caa-8cb7-47bb-8110-f83e5046b65e/01-Joan_Garcia-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('szczesny','Войцех Щенсны','Вратарь',13) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('szczesny','/portraits/szczesny.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/eb96038d-1fc9-4a98-8f40-b81944d057e6/25-Szczesny-RED.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('livakovic','Доминик Ливакович','Вратарь',25) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('livakovic','/portraits/livakovic.png','https://www.fcbarcelona.com/photo-resources/2026/08/26/364ac22a-cb07-44fb-8a38-4eb9385e0eb7/Livakovic-blau.png?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('cancelo','Жоау Канселу','Защитник',2) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('cancelo','/portraits/cancelo.jpg','https://www.fcbarcelona.com/photo-resources/2026/08/19/be6d271c-7704-4848-bc10-1a38924d4d60/00-Cancelo.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('balde','Алехандро Бальде','Защитник',3) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('balde','/portraits/balde.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/f8b0225c-2508-431c-baca-b66b97ec6e8e/03-Balde-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('cubarsi','Пау Кубарси','Защитник',5) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('cubarsi','/portraits/cubarsi.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/e96de4b6-5d94-400e-9f70-d1f745243818/02-Cubarsi-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('espart','Хави Эспарт','Защитник',12) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('espart','/portraits/espart.png','https://www.fcbarcelona.com/photo-resources/2026/08/26/ac515f82-5b62-4f2a-8a19-d0bb6ba13e63/12-XAVI_ESPART.png?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('christensen','Андреас Кристенсен','Защитник',15) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('christensen','/portraits/christensen.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/7b358e10-138f-4526-8cf8-34a26d6797c8/15-Christensen-RED.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('martin','Жерар Мартин','Защитник',18) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('martin','/portraits/martin.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/a37cf202-c22c-416d-87d7-e02cd73e39ad/18-Martin-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('kounde','Жюль Кунде','Защитник',23) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('kounde','/portraits/kounde.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/a51ceaf6-fd5e-495d-8217-322e7c319888/23-Kounde-RED.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('eric','Эрик Гарсия','Защитник',24) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('eric','/portraits/eric.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/b5cf8356-d686-4b7b-bf99-343f7c2a4454/24-Eric_Garcia-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('farinas','Бриан Фариньяс','Полузащитник',4) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('farinas','/portraits/farinas.jpg','https://www.fcbarcelona.com/photo-resources/2026/09/03/05fbff19-0b97-49bb-ac8b-92f1c816da51/04-Brian_Farinas-red.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('gavi','Гави','Полузащитник',6) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('gavi','/portraits/gavi.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/1691acd3-0765-4dfc-9296-a3320c24240a/06-Gavi-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('fermin','Фермин Лопес','Полузащитник',7) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('fermin','/portraits/fermin.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/cdd9f6c9-feb9-459c-bf84-1ea17e847cef/16-Fermin-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('pedri','Педри','Полузащитник',8) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('pedri','/portraits/pedri.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/c4a35ee4-35ef-4414-aff6-ed72ba8fce67/08-Pedri-RED.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('rodri','Родри','Полузащитник',16) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('rodri','/portraits/rodri.png','https://www.fcbarcelona.com/photo-resources/2026/08/18/4ad1a791-ce44-4734-bc29-e8cb8c4cf82e/00-Rodri-grana.png?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('olmo','Дани Ольмо','Полузащитник',20) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('olmo','/portraits/olmo.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/a150d470-f7ea-46d9-9f4d-a6295fef9d8d/20-Olmo-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('dejong','Френки де Йонг','Полузащитник',21) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('dejong','/portraits/dejong.png','https://www.fcbarcelona.com/photo-resources/2026/07/21/c6f44c49-1532-4041-bf76-0b80d48c2680/21-De_Jong-RED.png?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('bernal','Марк Берналь','Полузащитник',22) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('bernal','/portraits/bernal.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/e026c314-3284-4509-aae8-aac9f929c8e2/22-Bernal-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('jesus','Габриэл Жезус','Нападающий',9) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('jesus','/portraits/jesus.jpg','https://www.fcbarcelona.com/photo-resources/2026/09/03/20781c6e-5186-47ce-aa0c-f2d90c4d5085/09-Gabriel_Jesus-red.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('yamal','Ламин Ямаль','Нападающий',10) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('yamal','/portraits/yamal.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/323ae443-f58c-4e3d-bad5-e026d3175e81/10-Lamine-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('raphinha','Рафинья','Нападающий',11) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('raphinha','/portraits/raphinha.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/52cf522f-f115-4e64-8b22-6979d3687fae/11-Raphinha-RED.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('adeyemi','Карим Адейеми','Нападающий',14) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('adeyemi','/portraits/adeyemi.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/24/d7f6ac8e-1dd3-4cd5-9a79-6d2b1c3b21c0/00-Adeyemi-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('gordon','Энтони Гордон','Нападающий',17) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('gordon','/portraits/gordon.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/e22ebbbd-4707-423c-89f6-4ce7bbc34559/00-Gordon-RED.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('bardghji','Руни Бардагжи','Нападающий',19) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('bardghji','/portraits/bardghji.jpg','https://www.fcbarcelona.com/photo-resources/2026/07/21/bf80b46d-292c-4dea-b240-e63ad38d17b1/28-Bardghji-BLUE.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('bisiwu','Джесси Бисиву','Нападающий',27) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('bisiwu','/portraits/bisiwu.jpg','https://www.fcbarcelona.com/photo-resources/2026/08/04/63e8788b-a4e5-4d96-9dcb-718e9ef0f9c6/00-Bisiwu-red.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO players(id,name,role,number) VALUES('hamza','Хамза Абделькарим','Нападающий',29) ON CONFLICT(id) DO NOTHING;
INSERT INTO player_profiles(player_id,photo_path,photo_source,checked_on,active) VALUES('hamza','/portraits/hamza.jpg','https://www.fcbarcelona.com/photo-resources/2026/09/03/15566d63-53d3-4b35-8077-437adcaa1ed2/29-Hamza-blue.jpg?width=470&height=470','2026-09-07',1) ON CONFLICT(player_id) DO NOTHING;
INSERT INTO admins(user_id,role) SELECT '676858855','owner' WHERE NOT EXISTS(SELECT 1 FROM admins WHERE role='owner') ON CONFLICT(user_id) DO NOTHING;
COMMIT;
