import test from 'node:test';
import assert from 'node:assert/strict';
import {VoteQueue} from '../public/vote-queue.js';
import {contentDefaults,validateContent,richHtml,contentButton} from '../src/content.mjs';
import {openDatabase} from '../src/db.mjs';
import {seed} from '../src/seed.mjs';
import {Store} from '../src/store.mjs';
import {botHandlers} from '../src/bot.mjs';
test('Rich message preserves UTF-16 custom emoji and escapes text',()=>{const v=validateContent('intro','🔵 Привет <script>',[{type:'custom_emoji',offset:0,length:2,custom_emoji_id:'123456'},{type:'bold',offset:3,length:6}]);const html=richHtml(v);assert.ok(html.includes('<tg-emoji emoji-id="123456">🔵</tg-emoji>'));assert.ok(html.includes('<b>Привет</b>'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!richHtml(v,false).includes('tg-emoji'));});
test('Text validation rejects bad offsets, unsafe links, unknown keys and huge text',()=>{assert.throws(()=>validateContent('unknown','abc'));assert.throws(()=>validateContent('intro','a'.repeat(321)));assert.throws(()=>validateContent('intro','abc',[{type:'bold',offset:3,length:1}]));assert.throws(()=>validateContent('intro','abc',[{type:'text_link',offset:0,length:3,url:'javascript:alert(1)'}]));assert.throws(()=>validateContent('intro','abcdef',[{type:'bold',offset:0,length:4},{type:'italic',offset:2,length:4}]));});
test('Premium button has one icon and unambiguous label',()=>{const b=contentButton(validateContent('btn_vote','🔵 Оценить',[{type:'custom_emoji',offset:0,length:2,custom_emoji_id:'123'}]),'vote');assert.equal(b.text,'Оценить');assert.equal(b.icon_custom_emoji_id,'123');});
test('Rapid clicks stay selected and are coalesced while requests are in flight',async()=>{let release;const pending=new Promise(r=>release=r),sent=[];let version=0;const q=new VoteQueue({send:async scores=>{sent.push({scores,version});if(sent.length===1)await pending;return {version:version+1};},onSaved:b=>version=b.version,onStatus:()=>{},onError:e=>{throw e;}});q.put('a',1);q.put('b',3);q.put('b',5);q.put('c',4);release();await q.flush();assert.equal(sent.length,2);assert.deepEqual(sent[1],{scores:{b:5,c:4},version:1});assert.equal(version,2);});
test('Failed background save retains latest choices until explicit retry',async()=>{let fail=true;const sent=[];const q=new VoteQueue({send:async scores=>{sent.push(scores);if(fail)throw new Error('offline');return {};},onSaved:()=>{},onStatus:()=>{},onError:()=>{}});q.put('a',1);q.put('a',5);await q.flush();assert.equal(q.failed,true);assert.equal(q.pending.get('a'),5);fail=false;await q.retry();assert.deepEqual(sent.at(-1),{a:5});assert.equal(q.pending.size,0);});
test('Admin can preview and publish rich content; public user cannot',async t=>{const db=await openDatabase({sqlitePath:':memory:'});await seed(db,{demo:true,owner:'100'});const store=new Store(db);t.after(()=>db.close());await assert.rejects(store.setContent('200','intro','Changed'),{status:403});const calls=[],tg={call:async(method,payload)=>{calls.push({method,payload});return {photo:[{file_id:'file-'+calls.length}]};}},handlers=botHandlers(store,tg,{});const cb=data=>({callback_query:{id:'c',from:{id:100},message:{message_id:1,chat:{id:100,type:'private'}},data}});await handlers.handle(cb('edittext|intro'));await handlers.handle({message:{from:{id:100},chat:{id:100,type:'private'},text:'🔵 Привет',entities:[{type:'custom_emoji',offset:0,length:2,custom_emoji_id:'123'}]}});assert.equal((await store.content()).intro.text,contentDefaults.intro.text);await handlers.handle(cb('publish|intro'));assert.equal((await store.content()).intro.entities[0].custom_emoji_id,'123');await handlers.handle(cb('publish|intro'));assert.equal((await store.content()).intro.text,'🔵 Привет');});
test('Player navigation changes actual photo and prominent player name',async t=>{const db=await openDatabase({sqlitePath:':memory:'});await seed(db,{demo:true});const store=new Store(db);t.after(()=>db.close());const calls=[],tg={call:async(method,payload)=>{calls.push({method,payload});return {};}};const h=botHandlers(store,tg,{});await h.player(200,'200',5,'demo-valencia',0);await h.player(200,'200',5,'demo-valencia',1);assert.equal(calls[0].method,'editMessageMedia');assert.equal(calls[0].payload.get('photo').name,'garcia.jpg');assert.equal(calls[1].payload.get('photo').name,'kounde.jpg');assert.ok(JSON.parse(calls[1].payload.get('media')).caption.includes('ЖЮЛЬ КУНДЕ'));});

test('Loading caption replaces controls before player picker, without chat messages or toast',async t=>{
 const db=await openDatabase({sqlitePath:':memory:'});await seed(db,{demo:true});t.after(()=>db.close());const calls=[];
 const h=botHandlers(new Store(db),{call:async(method,payload)=>{calls.push({method,payload});return {};}},{});
 await h.handle({callback_query:{id:'loading',data:'pick|demo-valencia',from:{id:200},message:{message_id:17,chat:{id:200,type:'private'}}}});
 assert.equal(calls[0].method,'answerCallbackQuery');assert.equal(calls[0].payload.text,undefined);
 assert.equal(calls[1].method,'editMessageCaption');assert.equal(calls[1].payload.caption,'⏳ Открываем выбор игрока…');assert.deepEqual(calls[1].payload.reply_markup.inline_keyboard,[]);
 assert.equal(calls[2].method,'editMessageMedia');assert.equal(calls[2].payload.get('message_id'),'17');assert.ok(JSON.parse(calls[2].payload.get('media')).caption.includes('Чью оценку изменить'));
 assert.ok(!calls.some(c=>c.method==='sendMessage'||c.method==='sendPhoto'));
});
