import {readFile,writeFile} from 'node:fs/promises';
let js=await readFile('public/app.js','utf8');
js="import {VoteQueue} from './vote-queue.js';\n"+js;
js=js.replace("let toastTimer;","let toastTimer;\nconst plural=(n,one,few,many)=>`${n} ${n%100>=11&&n%100<=14?many:n%10===1?one:n%10>=2&&n%10<=4?few:many}`;");
js=js.replace('if(state.busy)return;state.view=view;','if(state.busy)return;if(!await waitForSaves())return;state.view=view;');
js=js.replace('state.id=select.value;state.detail=null;','if(!await waitForSaves()){select.value=state.id;return;}state.id=select.value;state.detail=null;');
js=js.replace('<div class="shirt-number">${p.number||\'—\'}</div>','${p.photo_path?`<img class="player-photo" src="${esc(p.photo_path)}" alt="" width="64" height="64" loading="lazy">`:`<div class="shirt-number">${p.number||\'—\'}</div>`}');
js=js.replace('<span>${esc(p.name)}</span><small>${esc(p.role)}</small>','${p.photo_path?`<img class="roster-photo" src="${esc(p.photo_path)}" alt="" loading="lazy">`:""}<span>${esc(p.name)}</span><small>${esc(p.role)}</small>');
js=js.replaceAll('Как сыграла Барса?','Оцени игроков').replaceAll('История только начинается','Пока нет результатов за сезон').replaceAll('Твой голос принят. Спасибо, Family!','✅ Оценки отправлены').replaceAll('Мнение сообщества','Оценки болельщиков').replaceAll('Рейтинг сезона учитывает только закрытые настоящие голосования.','Рейтинг сезона учитывает только завершённые голосования.').replaceAll('Результаты Family','Результаты голосования').replaceAll('Сезон Family','Рейтинг сезона').replaceAll('результаты Family','результаты голосования').replaceAll('каким этот матч запомнился Family','как болельщики оценили игроков').replaceAll('Сначала — твоё мнение','Сначала оцени игроков');
js=js.replace('${p.matches} матчей · ','${plural(p.matches,"матч","матча","матчей")} · ').replace('${p.votes} оценок','${plural(p.votes,"оценка","оценки","оценок")}').replace('${r.participants} участников','${plural(r.participants,"участник","участника","участников")}').replace('${r.matches} закрытых матчей','${plural(r.matches,"завершённый матч","завершённых матча","завершённых матчей")}');
const lines=js.split('\n');const index=lines.findIndex(l=>l.startsWith('async function saveScore('));if(index<0)throw new Error('saveScore not found');
lines[index]=`const voteQueue=new VoteQueue({
 send:scores=>api('/matches/'+state.id+'/votes',{scores,version:state.detail.ballot.version}),
 onSaved:b=>{state.detail.ballot.version=b.version;state.detail.ballot.submitted=b.submitted;},
 onStatus:()=>{const saving=$('#saving');if(saving)saving.textContent=voteQueue.failed?'Есть несохранённые оценки':voteQueue.running||voteQueue.pending.size?'Сохраняем…':'Сохранено';if(voteQueue.running||voteQueue.pending.size)tg?.enableClosingConfirmation?.();else tg?.disableClosingConfirmation?.();},
 onError:showSaveFailure
});
async function waitForSaves(){await voteQueue.flush();return !voteQueue.failed;}
function refreshChoices(){for(const p of state.detail.players){const score=state.detail.ballot.scores[p.id];document.querySelectorAll('[data-player="'+p.id+'"]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.score)===score));const clear=$('[data-clear="'+p.id+'"]');if(clear)clear.hidden=!score;}updateProgress();}
function saveScore(player,score){if(state.busy)return;if(score===null)delete state.detail.ballot.scores[player];else state.detail.ballot.scores[player]=score;refreshChoices();tg?.HapticFeedback?.selectionChanged();voteQueue.put(player,score);}
function showSaveFailure(e){const notice=$('#notice');notice.innerHTML=esc(e.message||'Не удалось сохранить оценки. Проверь подключение.')+'<br><button id="retry-save">Сохранить мои изменения</button> · <button id="reload-saved">Загрузить сохранённые оценки</button>';notice.hidden=false;
 $('#retry-save').onclick=async()=>{try{const remote=await api('/matches/'+state.id);if(remote.match.state!=='open')throw new Error('Голосование закрыто. Загрузи сохранённые оценки.');state.detail.ballot.version=remote.ballot.version;const merged={...remote.ballot.scores};for(const [id,score]of voteQueue.pending){if(score===null)delete merged[id];else merged[id]=score;}state.detail.ballot.scores=merged;clearError();refreshChoices();await voteQueue.retry();}catch(e){error(e);}};
 $('#reload-saved').onclick=async()=>{voteQueue.discard();clearError();await showVote();};
}
window.addEventListener('beforeunload',e=>{if(voteQueue.running||voteQueue.pending.size){e.preventDefault();e.returnValue='';}});`;
js=lines.join('\n');
js=js.replace("async function submit(){if(state.busy)return;", "async function submit(){if(state.busy)return;if(!await waitForSaves())return;");
js=js.replace('<button class="secondary" id="add-player">Добавить игрока в клуб</button>','<button class="secondary" id="add-player">Добавить игрока в клуб</button><button class="secondary" id="edit-content">✏️ Тексты бота</button>');
js=js.replace("$('#new-match').onclick=newMatch;", "$('#edit-content').onclick=()=>editContent().catch(error);$('#new-match').onclick=newMatch;");
js+=`\nasync function editContent(){const all=await api('/admin/content');$('#content').innerHTML='<button id="admin-back" class="back">← Все матчи</button><h2>Тексты бота</h2><p class="explanation">Здесь можно менять текст и обычные эмодзи. Премиум-эмодзи и форматирование добавляй в Telegram: /admin → «Тексты и эмодзи».</p><form id="content-form"><label class="field">Сообщение или кнопка<select id="content-key">'+Object.entries(all).map(([k,v])=>'<option value="'+esc(k)+'">'+esc(v.label)+'</option>').join('')+'</select></label><label class="field">Текст<textarea id="content-text" rows="7" required></textarea></label><p class="explanation" id="rich-warning"></p><button class="primary">Сохранить текст</button></form>';backBind();const load=()=>{const key=$('#content-key').value,c=all[key];$('#content-text').value=c.text;$('#content-text').maxLength=key.startsWith('btn_')?48:320;$('#rich-warning').textContent=c.entities?.length?'В сообщении есть форматирование или премиум-эмодзи. При изменении текста здесь они будут сняты. Чтобы сохранить их, редактируй сообщение через Telegram.':'';};load();$('#content-key').onchange=load;$('#content-form').onsubmit=async e=>{e.preventDefault();const key=$('#content-key').value,text=$('#content-text').value;try{await api('/admin/content',{key,text,entities:text===all[key].text?all[key].entities:[]});toast('Текст сохранён');await editContent();}catch(e){error(e);}};}\n`;
await writeFile('public/app.js',js);
let html=await readFile('public/index.html','utf8');html=html.replace('Матч закончился.<br>Твой голос —<br>в игре.','Оценки игроков<br>после матчей<br>Барселоны.').replace('Оцени тех, кто был на поле.<br>Соберём мнение всей Family.','От 1 до 5 каждому игроку.<br>Результаты матча и рейтинг сезона.').replace('Один клуб. Тысячи мнений.','Матчи · Игроки · Сезон').replace('Голос болельщиков','Оценки после матча').replace('Выходим на поле…','Загружаем голосование…').replace('Мнение сообщества','Оценки болельщиков');await writeFile('public/index.html',html);
let css=await readFile('public/style.css','utf8');css=css.replace('transition:width .2s ease-out','transition:none');css+=`\n.player-row{grid-template-columns:64px 1fr auto}.player-photo{width:64px;height:64px;object-fit:cover;border-radius:8px}.player-row .player-position{position:relative;padding-right:86px;min-height:18px}.clear-rating{position:absolute;right:0;top:-6px}.roster-photo{width:42px;height:42px;object-fit:cover;border-radius:6px}.field textarea{font:inherit;font-size:14px;line-height:1.7;display:block;width:100%;margin-top:10px;background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:14px;color:var(--white);resize:vertical}.field textarea:focus-visible{outline:3px solid var(--yellow);outline-offset:4px}.roster-choice small{max-width:100px}.roster-choice{gap:10px}\n@media(max-width:1000px){.player-row{grid-template-columns:64px 1fr}.rating-buttons{grid-column:1/-1}}\n@media(max-width:700px){.player-row{grid-template-columns:64px 1fr}.player-name{font-size:16px}.player-position{font-size:11px}.roster-choice small{max-width:70px;font-size:9px}}\n`;await writeFile('public/style.css',css);
console.log('Copy, portraits, background saves and admin text editor updated.');
